### ISSUE TITLE
Maple failing on CoolMUC2

### ISSUE THREAD

**Issue by vikaskurapati** [SeisSol/MatricesMaple#1]
Hi,

I am trying to generate "plasticity_ip_matrices_1.xml" for seissol order 1 implementation. SeisSol/Matrices does not have the implementation of plasticity matrices yet. So, I am trying to use the maple scripts implemented. When I run DGTools.mw, it returns the following error on CoolMUC's implementation of maple:

`> <?xml version="1.0" encoding="UTF-8"?>`
`on line 1 of "common/DGTools.mw", syntax error, character `?` unexpected:`
`<?xml version="1.0" encoding="UTF-8"?>`

Is there someone who can help me with this?

**Comment by Thomas-Ulrich** [comment]
Hi,
I find the way to reproduce your error, and the fix is easy:
You should not execute DGTools.mw with maple in the command line (`maple DGTools.mw `), but open the GUI of Maple (by executing `xmaple`) and execute the file there.

**Comment by vikaskurapati** [comment]
Hi,
Thanks! It seems to evaluate but I see nothing in the directory as an output. And then there are multiple DGTools.mw. We use the one from the Tetrahedra folder if I am not wrong. That is the one folder without a convert.py in it.

**Comment by Thomas-Ulrich** [comment]
When I run DGTools.mw (the one in common) a file DGTools.mla is created.
There is only one DGTools, it is in the common folder.

**Comment by vikaskurapati** [comment]
Do you have it installed on your computer or did you also try it on CoolMUC2? I just checked all the folders in the directory and there is no `DGTools.mla` after execution. I click execute and wait until it says Ready and then close maple GUI to check if the file is there somewhere
